### ISSUE TITLE
Matrix unter dem Punkt Messenger ergänzen

### ISSUE THREAD

**Issue by raketenlurch** [beschlagnahmt-org/beschlagnahmt#33]
Ohai,

Hab beim durchlesen festgestellt, dass unter dem Punkt Messenger zwar XMPP, aber nicht Matrix aufgeführt ist. Da ich die Erfahrung gemacht habe, dass Matrix für nicht-techaffine Personen häufig einfacher zu benutzen, würde ich das noch ergänzen wollen. Wenn das für Maintainer in Ordnung ist, könnte ich auch den Text beisteuern. :) 

LG
raketenlurch

**Comment by beschlagnahmt** [comment]
Sehr gerne!

**Comment by Le1b1** [comment]
> Wenn das für Maintainer in Ordnung ist, könnte ich auch den Text beisteuern.

Bitte maximal 3 Sätze, wir wollen hier bewusst keine ausführliche Sammlung von allen Messengern / Protokollen machen, sondern Orientierung bieten. :-)
