### ISSUE TITLE
Irreführende Info zu Samsung-Smartphones und Verschlüsselung

### ISSUE THREAD

**Issue by lxsycht** [beschlagnahmt-org/beschlagnahmt#34]
Hi. Cooles Projekt.

Im Abschnitt [Verschlüsselung](https://github.com/beschlagnahmt-org/beschlagnahmt/blob/master/_posts/2000-01-01-070-dateien-verschluesseln.md) gibt es diesen Hinweis zur Verschlüsselung von Smartphones:

> warning Fallstrick beim Handy-Verschlüsseln warning
> Wenn du ein Smartphone von Samsung hast wird das mit der Verschlüsselung leider etwas unpraktisch. Normalerweise musst du dein Entschlüsselungspasswort nur beim Starten des Geräts eingeben. Während es an ist kannst du dann deinen normalen Lockscreen benutzen. Samsung zwingt dich aber das Passwort jedes mal einzugeben wenn du den Bildschirm entsperren willst. Ziemlich unpraktisch und verleitet dazu ein unsicheres Passwort zu benutzen.

Das ist so nicht ganz korrekt, bzw. hat das nichts mit Samsung zu tun sondern mit der Verschlüsselungsmethode: Ältere Geräte unterstützen nur sogenannte Full Disk Encryption (FDE), bei der das Gerät beim hochfahren einmalig entschlüsselt werden muss und der Schlüssel im RAM gespeichert wird (so wie bei herkömmlicher PC/Laptop verschlüsselung). 

Neuere Hardware und Android-Versionen (mandatory ab Android 10) verschlüsseln dagegen mit File Based Encryption (FBE). Bei FBE muss nicht beim hochfahren der Speicher entschlüsselt werden, was den Vorteil hat dass man auf grundlegende Funktionen wie Wecker, telefonische Erreichbarkeit etc nicht verzichten muss. Es werden lediglich bestimmte Dateien bzw. Arten von Daten beim Entsperren ent-, und beim Sperren wieder verschlüsselt, (andere Teile bleiben über den laufenden Betrieb unverschlüsselt) und der Schlüssel hierfür bei jedem Sperren aus dem RAM geleert. 

Anders als bei FDE ist dadurch, bei korrekter Implementation und vorausgesetzt, dass keine Einfallstore wie Android-Debugging-Schnittstelle etc ausgenutzt werden können, auch eingeschaltete aber gesperrte Geräte vor dem Auslesen geschützt. Bei FBE gibt es kein seperates Boot-Passwort gegenüber der Bildschirmsperre.

FDE wird auch oberflächlich in dem im Abschnitt [verlinkten Artikel](https://proprivacy.com/privacy-service/guides/encryption-guide-to-securing-android-phone) zu Android angesprochen.

Mehr Hintergründe dazu hier:
https://blog.cryptographyengineering.com/2016/11/24/android-n-encryption/
und hier:
https://source.android.com/security/encryption/file-based

**Comment by lxsycht** [comment]
Ach, wenn erwünscht kann ich gern nen kleinen Infotext etwa wie diese Issue-Beschreibung beisteuern. Ist ja immerhin auch sicherheitsrelevant.

**Comment by Le1b1** [comment]
Danke, @lxsycht 
Der gesamte Abschnitt zu Smartphones ist nicht mehr ganz aktuell. Habe schon überlegt ob das überhaupt noch zeitgemäß ist eine Anleitung dazu drin zu haben. Immerhin ist FDE oder FBE schon seit Jahren (?) per Default bei den Geräten aktiviert. 
Habe aber noch keine Statistik dazu gesehen, so es denn überhaupt eine gibt.
Was meinst Du dazu?

**Comment by beschlagnahmt** [comment]
Ich fände es gut den Abschnitt zu updaten und dann primär nur noch auf den aktuellen Stand einzugehen. Wenn wir eine Anleitung weglassen können wir ja trotzdem noch erklären was so im Moment Standard ist und welche Sicherheit das bietet oder nicht bietet.

Zu alten Geräten: Ich glaube es gibt schon noch einige Leute die noch so alte Geräte verwenden, zumindest eine Randnotiz dazu fände ich also cool.

**Comment by Le1b1** [comment]
Ich finde es macht Sinn das Thema in 2 Seiten zu splitten, sonst wird es imho zu unübersichtlich:
 1. Gerätespeicher verschlüsseln
  * Richtige Passwort-Länge wählen (PCs / Smartphones)
  * Verschlüsselung aktivieren / überprüfen (iOS, Android, Win10, MacOS, Ubuntu)
2. Dateien verschlüsseln
  * VeraCrypt

**Comment by r0qstr** [comment]
kurzer einwurf: FDE ist unter lineage mWn nicht per default aktiviert
