### ISSUE TITLE
Enigmail für Thunderbird ist ab Version 72 EOL

### ISSUE THREAD

**Issue by raketenlurch** [beschlagnahmt-org/beschlagnahmt#35]
Da Enigmail für Thunderbird ab der Beta von Thunderbird 72 EOL ist und Thunderbird ab Version 78 direkten OpenPGP Support hat sollte der folgende Abschnitt imho überarbeitet werden:
`Verschlüsselte Kommunikation mit Thunderbird und Enigmail (Win & Linux):
Thunderbird installieren und mit deinem E-Mail-Konto verbinden
GPG (Linux) oder GPG4Win (Windows) installieren
Mit dem Thunderbird Addon-Manager Enigmail installieren
Thunderbird neustarten
Im Setup Wizard “Standard Configuration” auswählen und den Schritten folgen
Bei der Schlüsselerstellung die gewünschte E-Mail adresse aus der Liste auswählen
ggf. Passphrase eingeben
Warten bis die Schlüssel generiert wurden
Schlüssel können über das Menü “Enigmail -> Key Management” importiert und exportiert werden.
An dich gerichtete verschlüsselte Nachrichten werden beim Empfang automatisch entschlüsselt
E-Mails die du schreibst sollten automatisch verschlüsselt werden sofern du den entsprechenden öffentlichen Schlüssel importiert hast. Achte auf das Schloss Symbol über der E-Mail.
`

Source: https://www.enigmail.net/index.php/en/home/news/70-2019-10-08-future-openpgp-support-in-thunderbird
https://blog.thunderbird.net/2019/10/thunderbird-enigmail-and-openpgp/

**Comment by Le1b1** [comment]
Danke für den Hinweis, siehe https://github.com/beschlagnahmt-org/beschlagnahmt/issues/30.

**Comment by raketenlurch** [comment]
Uff. Bin anscheinend zu blöd um richtig zu lesen. Sorry für den Spam.

**Comment by Le1b1** [comment]
Alles gut, kommt vor :-)
