### ISSUE TITLE
Formatierung/Strukturierung

### ISSUE THREAD

**Issue by schtiehve** [beschlagnahmt-org/beschlagnahmt#38]
Ich glaube ein wenig Formatierung/Strukturierung würde längeren Seiten wie z.B. dateien-verschluesseln lesbarer machen.
Mein Vorschlag hierzu wäre:
Markdown überschriften verwenden
Bei Längeren Seiten/Seiten mit mehreren Teilbereichen eine TOC am Anfang einfügen:

```
* TOC
{:toc}
```
Wenn ihr das für Sinvoll haltet würde ich mich da mal ran machen und dann nen entsprechenden pull request reinstellen :wink:

**Comment by beschlagnahmt** [comment]
Das klingt sinnvoll. Was die TOC angeht müssten wir vielleicht in Zukunft schauen wie gut Pandoc damit klarkommt (https://github.com/beschlagnahmt-org/beschlagnahmt/pull/25) aber falls das Probleme macht bietet Pandoc ja auch die Option das vorher wieder rauszufiltern.
