### ISSUE TITLE
Passwörter mit KeePassXC verwalten

### ISSUE THREAD

**Issue by rrmelcer** [beschlagnahmt-org/beschlagnahmt#50]
**KeePass durch KeePassXC ersetzten**

Ein modernerer und chicerer Workflow der m.M.n. wenige fehleranfällig und einen zugänglicher Weg ist.

* [KeePassXC](https://keepassxc.org/) (Win-, Mac- & Linux Desktop)
* KeePassXC Plugin für [Firefox](https://addons.mozilla.org/de/firefox/addon/keepassxc-browser/) & [Chrome](https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk) (Chromium)
* [KeePassDX](https://www.keepassdx.com/) (Android)
* [Syncthing](https://syncthing.net/) für die Gerätesynchronisation ohne Server
* Passphrase (min 6 Wörter) & Keyfile für den Zugang
* Websrvices Zugang über TOTP 2FA getrennt über [Aegis](https://getaegis.app/)

**Comment by Le1b1** [comment]
Ich bin dran... 😃 
https://github.com/beschlagnahmt-org/beschlagnahmt/blob/KeePassXC/_posts/2000-01-01-150-passwort-manager.md
