### ISSUE TITLE
Vorschaubilder für OpenGraph Tags anpassen

### ISSUE THREAD

**Issue by sbstjn** [beschlagnahmt-org/beschlagnahmt#55]
Moin,
Das Bild für `og:image` sollte `1200x630` haben. Ebenso sollte das Bild für die Twitter Tags angepasst werden.

Hast du die Ursprungsdatei zu dem aktuell verwendeten Bild? Falls ja, pack sie doch mal ins Repo und ich kümmer mich gerne drum.

**Comment by Le1b1** [comment]
@sbstjn Das sollte https://github.com/beschlagnahmt-org/beschlagnahmt/blob/master/assets/cover/acab.png sein, oder?

**Comment by beschlagnahmt** [comment]
Ich hab gerade noch mal ausführlich gesucht, aber leider existiert die Originaldatei nicht mehr.

**Comment by Le1b1** [comment]
Nicht perfekt, aber es funktioniert: https://github.com/beschlagnahmt-org/beschlagnahmt/commit/53bfb03415a781b2de4adc5c38e449e3b6d2fe38
