### ISSUE TITLE
Quellenangaben / Copyright für Bilder fehlt

### ISSUE THREAD

**Issue by Le1b1** [beschlagnahmt-org/beschlagnahmt#8]
- [ ] https://beschlagnahmt.org/assets/posts/beschlagnahme.jpg

- [ ] https://beschlagnahmt.org/assets/posts/phineas.jpg

- [ ] https://beschlagnahmt.org/assets/posts/kommunikationsueberwachung.jpg

- [ ] https://beschlagnahmt.org/assets/posts/vpn.jpg

- [ ] https://beschlagnahmt.org/assets/posts/imsi-catcher.jpg

- [ ] https://beschlagnahmt.org/assets/posts/cloud-analyzer.jpg

**Comment by beschlagnahmt** [comment]
Habe zu den betreffenden Bildern recherchiert, PR mit den entsprechenden Änderungen folgt.

https://beschlagnahmt.org/assets/posts/beschlagnahme.jpg -> Lizenz unbekannt
-> Alternative: Selbst Screenshot von Autopsy/Sleuth Kit machen

https://beschlagnahmt.org/assets/posts/phineas.jpg -> Angefragt bei @cooperq@twitter.com, kann frei verwendet werden

https://beschlagnahmt.org/assets/posts/kommunikationsueberwachung.jpg -> Creative Commons BY-NC-SA 4.0. Netzpolitik.org

https://beschlagnahmt.org/assets/posts/vpn.jpg -> Lizenz unbekannt
-> Alternative: Selbst machen

https://beschlagnahmt.org/assets/posts/imsi-catcher.jpg -> Lizenz unbekannt
-> Alternative: https://bccla.org/wp-content/uploads/2016/08/IMSI-Catchers.jpg Creative Commons BY-NC-SA 2.5 Canada. BC Civil Liberties Association

https://beschlagnahmt.org/assets/posts/cloud-analyzer.jpg -> Lizenz unbekannt
-> Alternative: Selbst Screenshot von Greenwolfs social_mapper und/oder pimeyes.com machen
